# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # For all packages, ignore all patch updates, the "version-update" only targets non-security related updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Hacky workaround to get internal updates sooner, see also https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-2354999641
  - package-ecosystem: "pip"
    target-branch: main  # This is the hacky part...
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "Europe/Vienna"
    open-pull-requests-limit: 10
    versioning-strategy: increase  # always bump lower bound
    labels:
      - "dependencies"
    allow:
      # Only match internal dependencies
      - dependency-name: "astar*"
      - dependency-name: "scopesim*"
      - dependency-name: "spextra"
      - dependency-name: "skycalc-ipy"
      - dependency-name: "anisocado*"
    cooldown:
      # Don't include too new versions
      default-days: 7
      semver-patch-days: 2

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    versioning-strategy: increase  # always bump lower bound
    labels:
      - "dependencies"
    allow:
      # Allow both direct and indirect updates for all packages.
      - dependency-type: "direct"
    ignore:
      # Specific to this project
      # Don't need every minor update of those
      - dependency-name: "astropy"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "more-itertools"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      # Usually don't need patches here
      - dependency-name: "matplotlib"
        update-types: ["version-update:semver-patch"]
      # Those are less important generally
      - dependency-name: "docutils"
      - dependency-name: "beautifulsoup4"
      - dependency-name: "lxml"
      - dependency-name: "packaging"
    cooldown:
      # Don't include too new versions
      semver-major-days: 100
      semver-minor-days: 50
      semver-patch-days: 10
    groups:
      main-dependencies:
        # Applies to all dependencies defined in the main section of pyproject.toml
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "patch"
      dev-dependencies:
        # Applies to all dependencies defined in the dev section of pyproject.toml
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
