language: python
jobs:
  include:
    - name: python 3.5
      dist: trusty
      python: 3.5
      install:
        - pip install -r requirements.py35.travis.txt
        - pip install .

    - name: python 3.6
      dist: xenial
      python: 3.6
      install:
        - pip install -r requirements.py36.travis.txt
        - pip install .

    - name: python 3.7
      dist: xenial
      python: 3.7
      install:
        - pip install -r requirements.py37.travis.txt
        - pip install .

    - name: python 3.8
      dist: bionic
      python: 3.8
      install:
        - pip install -r requirements.py38.travis.txt
        - pip install .

script: 
  - pytest
  # - pytest --doctest-modules
  # scopesim_templates is used in the notebooks, but it depends on scopesim,
  # so it cannot be a requirement itself.
  - pip install scopesim_templates
  - jupyter nbconvert --execute docs/source/_static/scopesim_basic_intro.ipynb
  - jupyter nbconvert --execute "docs/source/_static/ScopeSim meets Astrometry.ipynb"
