#!/usr/bin/env python3
"""
ScopeSim: A python package to simulate telescope observations
"""

from datetime import datetime
from distutils.core import setup
import pytest  # not needed, but stops setup being included by sphinx.apidoc

# Version number
MAJOR = 0
MINOR = 1
ATTR = 'dev0'

VERSION = '%d.%d%s' % (MAJOR, MINOR, ATTR)


def write_version_py(filename='scopesim/version.py'):
    """Write a file version.py"""
    cnt = """
# THIS FILE GENERATED BY SCOPESIM SETUP.PY
version = '{}'
date    = '{}'
"""
    timestamp = datetime.utcnow().strftime('%Y-%m-%d %T GMT')
    with open(filename, 'w') as fd:
        fd.write(cnt.format(VERSION, timestamp))


def setup_package():
    # Rewrite the version file every time
    write_version_py()

    setup(name = 'ScopeSim',
          version = VERSION,
          description = "Telescope observation simulator",
          author = "Kieran Leschinski, Oliver Czoske, Miguel Verdugo",
          author_email = """kieran.leschinski@unive.ac.at,
                            oliver.czoske@univie.ac.at,
                            miguel.verdugo@univie.ac.at""",
          url = "http://homepage.univie.ac.at/kieran.leschinski/",
          package_dir={'scopesim': '.'},
          packages=['scopesim'],
          package_data = {'scopesim': []},
          )


if __name__ == '__main__':
    setup_package()
