name: Bump package version
on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Only output new version number, no actual change.
        required: false
      rule:
        type: choice
        description: Version bump level (ignored if explicit version is given)
        required: true
        options:
        - dev
        - prepatch
        - preminor
        - premajor
        - patch
        - minor
        - major
      version:
        type: string
        description: Explicit version (overrides rule), e.g. "X.Y.Zb0" to enter feature freeze.
        required: false
        default: ""

jobs:
  Bump:
    name: Bump version number
    uses: AstarVienna/DevOps/.github/workflows/bump.yml@main
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run }}
      rule: ${{ inputs.version != '' && inputs.version || inputs.rule }}
