name: Check Markdown links

on:
  push:
  schedule:
    - # Run every day at 5:00 UTC
    - cron: "0 5 * * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
