name: Notebooks with IRDB git clone

on:
  push:
    branches:
      - master
      - dev_master
      - dev_spectroscopy
  pull_request:
    branches:
      - master
      - dev_master
      - dev_spectroscopy

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run every night
  schedule:
    - cron: "0 2 * * *"


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Run only on a minimal subset of the matrix, as this is ran on many
        # commits.
        os: [ubuntu-latest]
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install this version of ScopeSim. Otherwise the PyPI version of
          # ScopeSim will be installed when the test-requriments
          # are installed, because ScopeSim is a dependency of
          # ScopeSim_Templates.
          pip install .
          pip install .[dev,test]
      - name: Run notebooks
        env:
          TQDM_MININTERVAL: 3
          # TQDM_POSITION: -1
        run: ./runnotebooks.sh --checkout-irdb --delete
