name: Notebooks with IRDB download

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run every night
  schedule:
    - cron: "0 3 * * *"


jobs:
  call-notebooks-without-clone:
    uses: ./.github/workflows/notebooks_dispatch.yml
