name: Notebooks with IRDB git clone

on:
  push:
    branches:
      - master
      - dev_master
      - dev_spectroscopy
  pull_request:
    branches:
      - master
      - dev_master
      - dev_spectroscopy

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run every night
  schedule:
    - cron: "0 2 * * *"


jobs:
  call-notebooks-with-clone:
    uses: ./.github/workflows/notebooks_dispatch.yml
    with:
      clone-irdb: true
