name: Notebooks with IRDB download

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run every night
  schedule:
    - cron: "0 3 * * *"


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Run all operating systems, because this is the first interaction
        # that users have with ScopeSim / IRDB.
        # However, only use minimum and maximum supported Python version,
        # as the IRDB download often fails.
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install this version of ScopeSim. Otherwise the PyPI version of
          # ScopeSim will be installed when the test-requriments
          # are installed, because ScopeSim is a dependency of
          # ScopeSim_Templates.
          pip install .
          pip install .[dev,test]
      - name: Run notebooks
        # No --checkout-irdb to download the IRDB as a normal end user would.
        run: ./runnotebooks.sh --delete
